### PR TITLE
Feature max dkp per slot and selectable max button behavior 

### PR DESCRIPTION
**Pull request by lantisnt**
Changes are intended for Minimum Bid Value mode (and zero sum with minimum bid).

1. Extended Maximum bid to be settable per slot (by default) and per item - same way as for min value. Setting 0 means no maximum value.
2. Maximum value is also announced if set
3. MAX Bid button behavior is now selectable:
- Max DKP - same as earlier, default
- Max Item value - to set current bid to max item value set. Sets to max DKP if no max item value
- Min(Max DKP, Max Item value) - set current bid to lower of the two above. Intended to use when going subzero with dkp is not allowed. If no max item value is set then sets bid to max DKP.
4. All above changes are localized for all languages. 
5. Max Item value and default per slot values are saved in variables same as minimum values.
6. Max item behavior is also saved.

### CODE REVIEW

**Comment by Roeshambo** [comment]
Adjusted default max values to 0 so as to not force the setting on anyone unknowingly.

**Comment by Roeshambo** [comment]
Did not have time to test this; but are there conflicts with older versions that do not utilize max values? I would assume not if they work identically to min values.

**Comment by lantisnt** [comment]
Hey. I found no conflicts when testing. This doesn't change max value behavior, only makes it selectable per Item. Only drawback will be that old max value set will be lost when updating. Thinking of nowa i could have implemented mrchanism to use it aa default value when migrating.

However this change altered communication protocol to include max value thus all raid members should have it updated.

**Comment by caspervk** [comment]
@Roeshambo when will this be available on Curse? Our guild uses the same bidding system as @lantisnt's (https://github.com/Roeshambo/MonolithDKP/issues/288), and thus we are also forced to use the 'Minimum Bid Value' system in an unintended way to get the desired functionality.

**Pull request merged**
